### ISSUE TITLE
Snippet is not work.

### ISSUE THREAD

**Issue by dspaudio** [gerardroche/sublime-php-grammar#99]
when I Installed this plugin, php snippet is not working.

**Comment by gerardroche** [comment]
Snippets are not included with this package. Nor are the completions.

Install [PHP Snippets](https://packagecontrol.io/packages/php-snippets) and [PHP Completions](https://packagecontrol.io/packages/PHP%20Completions%20Kit).

https://github.com/gerardroche/sublime-php-grammar#installation

**Comment by dspaudio** [comment]
I mean My snippet is not working when I installed this plugin

**Comment by gerardroche** [comment]
I need more information.

- OS, Sublime Text version, packages installed? You can get this info from the console log: `Menu > View > Show Console`
- Post the snippet that won't work.
- Explain what context it won't work in e.g. the code where it won't work, what you're pressing to trigger the snippet, where the cursor is when it won't work, etc.

I need as much information as possible to try to reproduce it.

**Comment by dspaudio** [comment]
Here's the console,

```
startup, version: 3118 osx x64 channel: dev
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/wknam/Library/Application Support/Sublime Text 3/Packages
state path: /Users/wknam/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/wknam/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Bootstrap 3 Snippets", "ConvertToUTF8", "PHP", "SublimeNFDToNFCPaste", "Vintage"]
pre session restore time: 0.516812
using gpu buffer for window
first paint time: 0.667919
startup time: 0.674939
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin Alignment.Alignment
reloading plugin All Autocomplete.all_views_completions
reloading plugin AngularJS.AngularJS-sublime-package
reloading plugin AngularJS.jscompletions
reloading plugin AngularJS.message
reloading plugin AngularJS.sublime_commands
reloading plugin AngularJS.viewlocation
reloading plugin ApplySyntax.ApplySyntax
reloading plugin Autoprefixer.Autoprefixer
reloading plugin Blade Spacer.BladeSpacer
reloading plugin BoundKeys.boundkeys
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_support
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin Colorsublime.colorsublime-plugin
reloading plugin Composer.composer
some modules could not be inported (it is ok if using ST3
reloading plugin Composer.composer_st3
reloading plugin DashDoc.DashDoc
reloading plugin DocBlockr.jsdocs
reloading plugin EasyMotion.easy_motion
reloading plugin Emmet.emmet-plugin
reloading plugin ExtendedTabSwitcher.ExtendedSwitcher
reloading plugin Fix Mac Path.FixPath
reloading plugin Function Name Display.FunctionNameStatus
reloading plugin Git-StatusBar.git-statusbar
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_change
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_helper
reloading plugin GitGutter.view_collection
reloading plugin Hex to HSL Color Converter.Hex-to-HSL-color
reloading plugin Hex to HSL Color Converter.RGB-to-HSL-color
reloading plugin HTML Nest Comments.HTMLNestComments
reloading plugin Keymaps.Keymaps
reloading plugin Laravel 5 Artisan.Laravel 5 Artisan
reloading plugin Minifier.Minify
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Package Syncing.Package Syncing
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin PHP Companion.PHP Companion
reloading plugin php-grammar.plugin
reloading plugin PhpDoc.CodeDoc
reloading plugin Preference Helper.Preference Helper
reloading plugin SCSS.scss_completions
reloading plugin Select Quoted.select_quotes
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarGit.SideBarAPI
reloading plugin SideBarGit.SideBarGit
reloading plugin SideBarGit.SideBarGitCommands
reloading plugin Subhub.subhub
Staring subhub server on port 48666
reloading plugin SublimeGit.SublimeGit
reloading plugin SublimeLinter-php.linter
SublimeLinter: php linter loaded 
reloading plugin SyncedSidebarBg.SyncedSidebarBg
reloading plugin Tag.Edit
reloading plugin Tag.Tag
reloading plugin Tag.tag_classes
reloading plugin Tag.tag_close_tag
reloading plugin Tag.tag_close_tag_on_slash
reloading plugin Tag.tag_indent
reloading plugin Tag.tag_insert_as_tag
reloading plugin Tag.tag_lint
reloading plugin Tag.tag_remove
reloading plugin Tag.tag_remove_attributes
reloading plugin Text Pastry.text_pastry
reloading plugin Text Pastry.text_pastry_addons
reloading plugin Text Pastry.text_pastry_selection
reloading plugin Toggle Css Format.ToggleCssFormat
reloading plugin Autoprefixer.node_bridge
reloading plugin CodeComplice.CodeComplice
reloading plugin CSScomb.CSScomb
reloading plugin Duplicate Lines.duplicate_lines
reloading plugin EncodingHelper.EncodingHelper
reloading plugin Gulp.base_command
reloading plugin Gulp.cross_platform_codecs
reloading plugin Gulp.dir_context
reloading plugin Gulp.event_task
reloading plugin Gulp.gulp
reloading plugin Gulp.gulp_version
reloading plugin Gulp.hasher
reloading plugin Gulp.plugins
reloading plugin Gulp.progress_notifier
reloading plugin Gulp.settings
reloading plugin Image2Base64.Image2Base64
reloading plugin LineSelect.LineSelect
reloading plugin SFTP.SFTP
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "ApplySyntax in /Users/wknam/Library/Application Support/Sublime Text 3/Installed Packages/ApplySyntax.sublime-package", line 668, in plugin_loaded
  File "ApplySyntax in /Users/wknam/Library/Application Support/Sublime Text 3/Installed Packages/ApplySyntax.sublime-package", line 634, in touch_untouched
  File "ApplySyntax in /Users/wknam/Library/Application Support/Sublime Text 3/Installed Packages/ApplySyntax.sublime-package", line 354, in on_touched
  File "ApplySyntax in /Users/wknam/Library/Application Support/Sublime Text 3/Installed Packages/ApplySyntax.sublime-package", line 371, in detect_syntax
  File "ApplySyntax in /Users/wknam/Library/Application Support/Sublime Text 3/Installed Packages/ApplySyntax.sublime-package", line 482, in syntax_matches
  File "ApplySyntax in /Users/wknam/Library/Application Support/Sublime Text 3/Installed Packages/ApplySyntax.sublime-package", line 536, in extension_matches
  File "./python3.3/posixpath.py", line 142, in basename
AttributeError: 'NoneType' object has no attribute 'rfind'
--------- <sublime.Settings object at 0x11041cbd0> ----------
False
True
True
./composer.phar
composer.json
['-n', '-v']
['-n', '-v']
['-n', '-v']
['-n', '-v']
['-n', '-v']
['-n', '-v']
SublimeLinter: debug mode: off 
SublimeLinter: php activated: /usr/local/bin/php 
reloading settings Packages/User/Package Syncing.sublime-settings
Traceback (most recent call last):
  File "git-statusbar in /Users/wknam/Library/Application Support/Sublime Text 3/Installed Packages/Git-StatusBar.sublime-package", line 122, in <lambda>
  File "git-statusbar in /Users/wknam/Library/Application Support/Sublime Text 3/Installed Packages/Git-StatusBar.sublime-package", line 128, in _update_status_bar
  File "git-statusbar in /Users/wknam/Library/Application Support/Sublime Text 3/Installed Packages/Git-StatusBar.sublime-package", line 106, in badge
  File "git-statusbar in /Users/wknam/Library/Application Support/Sublime Text 3/Installed Packages/Git-StatusBar.sublime-package", line 73, in branch
  File "git-statusbar in /Users/wknam/Library/Application Support/Sublime Text 3/Installed Packages/Git-StatusBar.sublime-package", line 54, in run_git
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'LaravelProject/Hansan'
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2016-07-17 09:05:00, next run at 2016-07-17 10:05:00 or after
Traceback (most recent call last):
  File "git-statusbar in /Users/wknam/Library/Application Support/Sublime Text 3/Installed Packages/Git-StatusBar.sublime-package", line 122, in <lambda>
  File "git-statusbar in /Users/wknam/Library/Application Support/Sublime Text 3/Installed Packages/Git-StatusBar.sublime-package", line 128, in _update_status_bar
  File "git-statusbar in /Users/wknam/Library/Application Support/Sublime Text 3/Installed Packages/Git-StatusBar.sublime-package", line 106, in badge
  File "git-statusbar in /Users/wknam/Library/Application Support/Sublime Text 3/Installed Packages/Git-StatusBar.sublime-package", line 73, in branch
  File "git-statusbar in /Users/wknam/Library/Application Support/Sublime Text 3/Installed Packages/Git-StatusBar.sublime-package", line 54, in run_git
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'LaravelProject/Hansan'
```


and I tried triggering this php file,

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class AdminController extends Controller
{
    lacon[tab]
}
```

and I get "action("ControllerName@method")"



Here's the snippet file


```
<snippet>
    <content><![CDATA[
public function __construct()
{
    ${1:\$this->middleware('auth');}
}

${2}
]]></content>
    <!-- Optional: Set a tabTrigger to define how to trigger the snippet -->
    <tabTrigger>lacon</tabTrigger>
    <!-- Optional: Set a scope to limit where the snippet will trigger -->
    <!-- <scope>source.php</scope> -->
    <scope>source.php - comment - constant.other.class - entity.name - meta.catch - meta.class - meta.function.arguments - meta.use - string - variable.other</scope>
    <description>Laravel auth constructor</description>
</snippet>
```

**Comment by fredrkr** [comment]
I'm getting the same. My own snippets are not listed in the auto complete window, and my tab-triggers are not working.

* OS X El Capitan 10.11.5
* ST3 3114
* I just installed php-grammar, so presumably it's the latest version.

Here's an example I just tested:

```php
<?php

abc[tab]
```

The snippet:

```xml
<snippet>
	<content><![CDATA[
A$1 B$2 C$3
]]></content>
	<tabTrigger>abc</tabTrigger>
	<scope>source.php</scope>
</snippet>
```

The file is located in  ```Sublime Text -> Preferences -> Browse Packages``` and then ```User/Snippets/PHP/abc.sublime-snippet```

Pressing [tab] in the above situation, either results in a space, tab (depending on settings) or inserts the currently selected item in the auto complete window (depending on wether there are any completions installed). I expect my snippet to be expanded in this case.

The scope in my php-file: ```embedding.php text.html.basic meta.embedded.block.php source.php```. Setting this to the snippet's scope has no effect. Indeed, removing the scope tag from the snippet so that it is global, yields no results. 

Please reopen this issue.

My console at launch:

```
startup, version: 3114 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/effkay/Library/Application Support/Sublime Text 3/Packages
state path: /Users/effkay/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/effkay/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["PHP", "Vintage"]
pre session restore time: 0.342114
using gpu buffer for window
startup time: 0.400812
first paint time: 0.418185
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin Alignment.Alignment
reloading plugin Better CoffeeScript.CoffeeScript
reloading plugin Blade Spacer.BladeSpacer
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_support
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin DocBlockr.jsdocs
reloading plugin Emmet.emmet-plugin
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin php-grammar.plugin
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-contrib-sass-lint.linter
SublimeLinter: sass linter loaded 
reloading plugin SublimeLinter-jshint.linter
SublimeLinter: jshint linter loaded 
reloading plugin SublimeLinter-json.linter
SublimeLinter: json linter loaded 
reloading plugin SublimeLinter-php.linter
SublimeLinter: php linter loaded 
reloading plugin TabSnippets.main
reloading plugin Trimmer.Trimmer
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-phpcs.linter
SublimeLinter: phpcs linter loaded 
reloading plugin SublimeLinter-phpmd.linter
SublimeLinter: phpmd linter loaded 
plugins loaded
SublimeLinter: debug mode: off 
Emmet: No need to update PyV8
recreating index
error: unable to open crawldb (~/Library/Application Support/Sublime Text 3/Index), indexing is unavailable
```

**Comment by gerardroche** [comment]
I'm unable to reproduce this, at least on Ubuntu. However, you are both using OSX. @dspaudio are you using El Capitan ~ 10.11.5 like @fredrkr ? 

It sounds very much like a package conflict or an ST issue. It doesn't sound like a php-grammar issue, but it's possible. 

Try disabling or remobing php-grammar (don't forget to manually reenable the PHP package after removing or disable php-grammar:  Goto User Preferences and remove "PHP" from `ignored_packages` list. Remember to close any open views and restart Sublime Text after enabling or removing. *Views are cached, so for example when you disable something to see if it fixes the issue you will likely get a false-positive because the view is cached.*

Does disabling or removing php-grammar solve the issue?

To debug it more:

* Do other snippets work? Do other completions work.
* Enable verbose logging: open the console `View > Show Console` and enter `sublime.log_input(True)` and `sublime.log_commands(DEBUG)`. Now the console will show much more information.
* @dspaudio you say that instead of getting the snippet completion you expect you get `action("ControllerName@method")`? This sounds like another snippet is overriding your custom one. Try changing the tab trigger to something like "fizzbuzz". Does that work?
* Try disabling all plugins, if that solves the issue, or if a clean ST install solves it, then try enabling or installing other one by one to find the plugin causing the conflict.


PS

@dspaudio From you logs I can see several of your packages are causing errors. It doesn't have anything to do with this issue, but I'd recommend disabling those and reporting the errors because it looks like they're not working anyway and probably causing other issues like performance.

**Comment by gerardroche** [comment]
If php-grammar before then it could be recent change in php-grammar. This could be tested by installing php-grammar via git: https://github.com/gerardroche/sublime-php-grammar#manual-installation and checking the last version tagged `0.20.0` to see if that works and the one before that `0.19.0`, etc.

**Comment by fredrkr** [comment]
* After removing php-grammar and re-enabling the default PHP bundle, my snippets work as expected.
* Completions from other 3rd party packages work. If I install your php-completions package, they appear in the auto complete popup window.
* Snippets from your php-snippets package work. They appear in the auto complete popup window. Example: I press 'rt[esc]' so that the popup window disappears, then press [tab], the snippet expands to ```return $this```.
* Enabling the verbose logging doesn't yield too much. Here's an example:

```
chr evt: a (0x61)
chr evt: b (0x62)
chr evt: c (0x63)
key evt: escape
command: hide_auto_complete
key evt: tab
command: insert_best_completion {"default": "	", "exact": true}
```

After removing php-grammar, and doing the exact same thing, the exact same is also displayed in the console with verbose logging. The difference being, of course, that my snippet is displayed in the auto complete popup and pressing tab actually expands my snippet.

**Comment by gerardroche** [comment]
Great. We've narrowed it to a regression probably specific to OSX.

I don't have a mac so I can't debug this. The way to debug it is installing php-manual manually via git and then step back through the commits to try and narrow the issue down to specific changes and then go from there.

**Comment by fredrkr** [comment]
Well I figured it out. Stepping back through your releases yielded nothing. The problem is **where** I'm keeping my snippet files. As I said in my first comment, the snippets are located in ```Sublime Text -> Preferences -> Browse Packages``` and then ```User/Snippets/PHP/*.sublime-snippet```. This is no problem for the built in PHP package. But php-grammar can only find snippet-files if they are located a maximum of one folder deep inside the User folder. That is, if I move my snippet files from ```User/Snippets/PHP``` to ```User/Whatever/```, it all works. This is true for the Windows-version of Sublime Text 3 as well, which I was able to test.

Does this make sense?

**Comment by gerardroche** [comment]
Very good. Yes it does make sense. 

php-grammar disables the PHP plugin, so any directory named PHP is ignored in user settings. It's the same on my system. And the same for any disabled plugin. If you disable say the "Vintage" plugin then that directory will ignored in the user directory.

All the following work:

* `User/abc.sublime-snippet`
* `User/fizz/abc.sublime-snippet`
* `User/fizz/buzz/abc.sublime-snippet`

But none inside a PHP directory work:

`User/PHP/abc.sublime-snippet`
`User/fizz/PHP/abc.sublime-snippet`
`User/fizz/buzz/PHP/abc.sublime-snippet`

**Comment by fredrkr** [comment]
Ah so that's what the problem was. Guess I'll just rename the folder, then :) Thanks!

**Comment by dspaudio** [comment]
Great!

I renamed User/PHP/abc.sublime-snippet to User/peehp/abc.sublime-snippet, then work.
maybe name of directory is the problem, I think.

**Comment by gerardroche** [comment]
Great. Thanks. 

Renaming that folder would be the way to go. I don't think there's any way I could workaround this.
